// lib/locations.js

export const LOCATIONS = [
  // ── Original entries (unchanged — existing listings & filters depend on these exact values) ──
  {
    value: "Choba (Back Gate)",
    label: "Choba (Back Gate)",
    hint: "Behind UST — most popular student area",
    mapQuery: "Choba, Port Harcourt, Nigeria",
  },
  {
    value: "Obirikwe (Main Gate)",
    label: "Obirikwe (Main Gate)",
    hint: "Front of UST campus",
    mapQuery: "Obirikwe, Port Harcourt, Nigeria",
  },
  {
    value: "Alakahia",
    label: "Alakahia",
    hint: "Close to Back Gate",
    mapQuery: "Alakahia, Choba, Port Harcourt, Nigeria",
  },
  {
    value: "Ozuoba",
    label: "Ozuoba",
    hint: "Along Back Gate road",
    mapQuery: "Ozuoba, Port Harcourt, Nigeria",
  },
  {
    value: "Mgbuoba",
    label: "Mgbuoba",
    hint: "Off Back Gate axis",
    mapQuery: "Mgbuoba, Port Harcourt, Nigeria",
  },
  {
    value: "Rumuola",
    label: "Rumuola",
    hint: "Trans-Amadi area",
    mapQuery: "Rumuola, Port Harcourt, Nigeria",
  },
  {
    value: "Rumuokoro",
    label: "Rumuokoro",
    hint: "Rumuokoro junction axis",
    mapQuery: "Rumuokoro, Port Harcourt, Nigeria",
  },
  {
    value: "Rumuigbo",
    label: "Rumuigbo",
    hint: "Off Aba Road",
    mapQuery: "Rumuigbo, Port Harcourt, Nigeria",
  },
  {
    value: "Woji",
    label: "Woji",
    hint: "Woji Road axis",
    mapQuery: "Woji, Port Harcourt, Nigeria",
  },
  {
    value: "GRA",
    label: "GRA",
    hint: "Government Reserved Area",
    mapQuery: "GRA, Port Harcourt, Nigeria",
  },
  {
    value: "Peter Odili",
    label: "Peter Odili",
    hint: "Peter Odili Road",
    mapQuery: "Peter Odili Road, Port Harcourt, Nigeria",
  },
  {
    value: "Eliozu",
    label: "Eliozu",
    hint: "Eliozu axis",
    mapQuery: "Eliozu, Port Harcourt, Nigeria",
  },
  {
    value: "Rumuepirikom",
    label: "Rumuepirikom",
    hint: "Off Aba Road",
    mapQuery: "Rumuepirikom, Port Harcourt, Nigeria",
  },

  // ── New entries (added from the fuller area list — same value/label convention) ──
  { value: "Old GRA", label: "Old GRA", hint: "", mapQuery: "Old GRA, Port Harcourt, Nigeria" },
  { value: "New GRA", label: "New GRA", hint: "", mapQuery: "New GRA, Port Harcourt, Nigeria" },
  { value: "D-Line", label: "D-Line", hint: "", mapQuery: "D-Line, Port Harcourt, Nigeria" },
  { value: "Port Harcourt Township", label: "Port Harcourt Township", hint: "", mapQuery: "Port Harcourt Township, Port Harcourt, Nigeria" },
  { value: "Diobu", label: "Diobu", hint: "", mapQuery: "Diobu, Port Harcourt, Nigeria" },
  { value: "Mile 1", label: "Mile 1", hint: "", mapQuery: "Mile 1, Port Harcourt, Nigeria" },
  { value: "Mile 2", label: "Mile 2", hint: "", mapQuery: "Mile 2, Port Harcourt, Nigeria" },
  { value: "Mile 3", label: "Mile 3", hint: "", mapQuery: "Mile 3, Port Harcourt, Nigeria" },
  { value: "Mile 4", label: "Mile 4", hint: "", mapQuery: "Mile 4, Port Harcourt, Nigeria" },
  { value: "Borokiri", label: "Borokiri", hint: "", mapQuery: "Borokiri, Port Harcourt, Nigeria" },
  { value: "Abuloma", label: "Abuloma", hint: "", mapQuery: "Abuloma, Port Harcourt, Nigeria" },
  { value: "Amadi Flats", label: "Amadi Flats", hint: "", mapQuery: "Amadi Flats, Port Harcourt, Nigeria" },
  { value: "Amadi-Ama", label: "Amadi-Ama", hint: "", mapQuery: "Amadi-Ama, Port Harcourt, Nigeria" },
  { value: "Elekahia", label: "Elekahia", hint: "", mapQuery: "Elekahia, Port Harcourt, Nigeria" },
  { value: "Ogbunabali", label: "Ogbunabali", hint: "", mapQuery: "Ogbunabali, Port Harcourt, Nigeria" },
  { value: "Oroworukwo", label: "Oroworukwo", hint: "Popular with RSU students", mapQuery: "Oroworukwo, Port Harcourt, Nigeria" },
  { value: "Rumuwoji", label: "Rumuwoji", hint: "Popular with RSU students", mapQuery: "Rumuwoji, Port Harcourt, Nigeria" },
  { value: "Rumuobiekwe", label: "Rumuobiekwe", hint: "Popular with RSU students", mapQuery: "Rumuobiekwe, Port Harcourt, Nigeria" },
  { value: "Rumueme", label: "Rumueme", hint: "Popular with RSU students", mapQuery: "Rumueme, Port Harcourt, Nigeria" },
  { value: "Rumuomasi", label: "Rumuomasi", hint: "Popular with RSU students", mapQuery: "Rumuomasi, Port Harcourt, Nigeria" },
  { value: "Nkpogu", label: "Nkpogu", hint: "Popular with RSU students", mapQuery: "Nkpogu, Port Harcourt, Nigeria" },
  { value: "Rainbow Town", label: "Rainbow Town", hint: "", mapQuery: "Rainbow Town, Port Harcourt, Nigeria" },
  { value: "Eagle Island", label: "Eagle Island", hint: "", mapQuery: "Eagle Island, Port Harcourt, Nigeria" },
  { value: "Marine Base", label: "Marine Base", hint: "", mapQuery: "Marine Base, Port Harcourt, Nigeria" },
  { value: "Bundu-Ama", label: "Bundu-Ama", hint: "", mapQuery: "Bundu-Ama, Port Harcourt, Nigeria" },
  { value: "Okuru-Ama", label: "Okuru-Ama", hint: "", mapQuery: "Okuru-Ama, Port Harcourt, Nigeria" },
  { value: "Orogbum", label: "Orogbum", hint: "", mapQuery: "Orogbum, Port Harcourt, Nigeria" },
  { value: "Umueme", label: "Umueme", hint: "", mapQuery: "Umueme, Port Harcourt, Nigeria" },
  { value: "New Layout", label: "New Layout", hint: "", mapQuery: "New Layout, Port Harcourt, Nigeria" },
  { value: "Oroabali", label: "Oroabali", hint: "", mapQuery: "Oroabali, Port Harcourt, Nigeria" },
  { value: "Rumukalagba", label: "Rumukalagba", hint: "Popular with RSU students", mapQuery: "Rumukalagba, Port Harcourt, Nigeria" },
  { value: "Rumuokwuta", label: "Rumuokwuta", hint: "Popular with RSU students", mapQuery: "Rumuokwuta, Port Harcourt, Nigeria" },
  { value: "Rumuodara", label: "Rumuodara", hint: "Popular with RSU students", mapQuery: "Rumuodara, Port Harcourt, Nigeria" },
  { value: "Rumuokwurusi", label: "Rumuokwurusi", hint: "Popular with RSU students", mapQuery: "Rumuokwurusi, Port Harcourt, Nigeria" },
  { value: "Rumuosi", label: "Rumuosi", hint: "Popular with RSU students", mapQuery: "Rumuosi, Port Harcourt, Nigeria" },
  { value: "Rumuosi/Rumuekini", label: "Rumuosi / Rumuekini", hint: "Popular with RSU students", mapQuery: "Rumuosi, Port Harcourt, Nigeria" },
  { value: "Rumuokurusi", label: "Rumuokurusi", hint: "Popular with RSU students", mapQuery: "Rumuokurusi, Port Harcourt, Nigeria" },
  { value: "Elelenwo", label: "Elelenwo", hint: "Popular with RSU students", mapQuery: "Elelenwo, Port Harcourt, Nigeria" },
  { value: "Ada George", label: "Ada George", hint: "Popular with RSU students", mapQuery: "Ada George, Port Harcourt, Nigeria" },
  { value: "Rukpokwu", label: "Rukpokwu", hint: "", mapQuery: "Rukpokwu, Port Harcourt, Nigeria" },
  { value: "Eneka", label: "Eneka", hint: "", mapQuery: "Eneka, Port Harcourt, Nigeria" },
  { value: "Rumunduru", label: "Rumunduru", hint: "Popular with RSU students", mapQuery: "Rumunduru, Port Harcourt, Nigeria" },
  { value: "Rumukrushi", label: "Rumukrushi", hint: "Popular with RSU students", mapQuery: "Rumukrushi, Port Harcourt, Nigeria" },
  { value: "Rumuekeni", label: "Rumuekeni", hint: "Popular with RSU students", mapQuery: "Rumuekeni, Port Harcourt, Nigeria" },
  { value: "Oginigba", label: "Oginigba", hint: "", mapQuery: "Oginigba, Port Harcourt, Nigeria" },
  { value: "Trans-Amadi", label: "Trans-Amadi", hint: "", mapQuery: "Trans-Amadi, Port Harcourt, Nigeria" },
  { value: "Trans-Amadi Industrial Layout", label: "Trans-Amadi Industrial Layout", hint: "", mapQuery: "Trans-Amadi Industrial Layout, Port Harcourt, Nigeria" },
  { value: "Elikpokwu-Odu", label: "Elikpokwu-Odu", hint: "", mapQuery: "Elikpokwu-Odu, Port Harcourt, Nigeria" },
  { value: "Iriebe", label: "Iriebe", hint: "", mapQuery: "Iriebe, Port Harcourt, Nigeria" },
  { value: "Agip", label: "Agip", hint: "", mapQuery: "Agip, Port Harcourt, Nigeria" },
  { value: "Rumuola/New GRA Axis", label: "Rumuola / New GRA Axis", hint: "Popular with RSU students", mapQuery: "Rumuola, Port Harcourt, Nigeria" },
  { value: "Oyigbo", label: "Oyigbo", hint: "Outside central Port Harcourt", mapQuery: "Oyigbo, Rivers State, Nigeria" },
  { value: "Eleme", label: "Eleme", hint: "Outside central Port Harcourt", mapQuery: "Eleme, Rivers State, Nigeria" },
  { value: "Onne", label: "Onne", hint: "Outside central Port Harcourt", mapQuery: "Onne, Rivers State, Nigeria" },
  { value: "Okrika", label: "Okrika", hint: "Outside central Port Harcourt", mapQuery: "Okrika, Rivers State, Nigeria" },
  { value: "Igbo-Etche", label: "Igbo-Etche", hint: "Outside central Port Harcourt", mapQuery: "Igbo-Etche, Rivers State, Nigeria" },
  { value: "Etche", label: "Etche", hint: "Outside central Port Harcourt", mapQuery: "Etche, Rivers State, Nigeria" },
  { value: "Isiokpo", label: "Isiokpo", hint: "Outside central Port Harcourt", mapQuery: "Isiokpo, Rivers State, Nigeria" },
  { value: "Igwuruta", label: "Igwuruta", hint: "Outside central Port Harcourt", mapQuery: "Igwuruta, Rivers State, Nigeria" },
  { value: "Aluu", label: "Aluu", hint: "Outside central Port Harcourt", mapQuery: "Aluu, Rivers State, Nigeria" },
  { value: "Rumuekpe", label: "Rumuekpe", hint: "Outside central Port Harcourt", mapQuery: "Rumuekpe, Rivers State, Nigeria" },
  { value: "Emohua", label: "Emohua", hint: "Outside central Port Harcourt", mapQuery: "Emohua, Rivers State, Nigeria" },

  {
    value: "Other",
    label: "Other",
    hint: "Anywhere else in Port Harcourt",
    mapQuery: "Port Harcourt, Nigeria",
  },
];

export const LOCATION_FILTER_OPTIONS = [
  { value: "All", label: "All Areas" },
  ...LOCATIONS,
];

export const UST_GATE_AREAS = [
  "Choba (Back Gate)",
  "Obirikwe (Main Gate)",
  "Alakahia",
  "Ozuoba",
  "Mgbuoba",
  "Oroworukwo",
  "Rumuwoji",
  "Rumuobiekwe",
  "Rumueme",
  "Rumuomasi",
  "Nkpogu",
  "Rumukalagba",
  "Rumuokwuta",
  "Rumuodara",
  "Rumuokwurusi",
  "Rumuosi",
  "Rumuosi/Rumuekini",
  "Rumuokurusi",
  "Elelenwo",
  "Ada George",
  "Rumunduru",
  "Rumukrushi",
  "Rumuekeni",
];

export const OTHER_PH_AREAS = [
  "Rumuola",
  "Rumuokoro",
  "Rumuigbo",
  "Woji",
  "GRA",
  "Peter Odili",
  "Eliozu",
  "Rumuepirikom",
  "Old GRA",
  "New GRA",
  "D-Line",
  "Port Harcourt Township",
  "Diobu",
  "Mile 1",
  "Mile 2",
  "Mile 3",
  "Mile 4",
  "Borokiri",
  "Abuloma",
  "Amadi Flats",
  "Amadi-Ama",
  "Elekahia",
  "Ogbunabali",
  "Rainbow Town",
  "Eagle Island",
  "Marine Base",
  "Bundu-Ama",
  "Okuru-Ama",
  "Orogbum",
  "Umueme",
  "New Layout",
  "Oroabali",
  "Rukpokwu",
  "Eneka",
  "Oginigba",
  "Trans-Amadi",
  "Trans-Amadi Industrial Layout",
  "Elikpokwu-Odu",
  "Iriebe",
  "Agip",
  "Rumuola/New GRA Axis",
  "Oyigbo",
  "Eleme",
  "Onne",
  "Okrika",
  "Igbo-Etche",
  "Etche",
  "Isiokpo",
  "Igwuruta",
  "Aluu",
  "Rumuekpe",
  "Emohua",
  "Other",
];

// Universities in Port Harcourt
export const UNIVERSITIES = [
  { value: "All", label: "Any School" },
  { value: "UST", label: "Rivers State University (RSU/UST)" },
  { value: "UniPort", label: "University of Port Harcourt (UniPort)" },
  { value: "IAUE", label: "Ignatius Ajuru University (IAUE)" },
  { value: "KenSaro", label: "Ken Saro-Wiwa Polytechnic" },
  { value: "RSFCOLLEGE", label: "Rivers State College of Arts & Science" },
  { value: "Other", label: "Other School" },
];

// Maps university to the areas students from that school typically live
// Used as fallback when listing has no nearSchool field
export const UNIVERSITY_AREA_MAP = {
  UST: ["Choba (Back Gate)", "Obirikwe (Main Gate)", "Alakahia", "Ozuoba", "Mgbuoba"],
  UniPort: ["Choba (Back Gate)", "Alakahia", "Ozuoba", "Rumuola", "Rumuokoro"],
  IAUE: ["Rumuola", "Rumuokoro", "Eliozu", "Rumuigbo"],
  KenSaro: ["Bori", "Rumuola", "Other"],
  RSFCOLLEGE: ["Rumuola", "Peter Odili", "GRA"],
  Other: [],
};